// GENERATED by @pocketjs/aot (gb backend) — do not edit.
#ifndef PJ_GEN_DATA_H
#define PJ_GEN_DATA_H
#include <gbdk/platform.h>

typedef struct { unsigned int x, y; unsigned char sprite, facing, move, flags; unsigned int on_talk, rsv; } PjActor;
typedef struct { unsigned int x, y; unsigned char dest_map, dest_dir; unsigned int dest_x, dest_y, rsv; } PjWarp;
typedef struct { unsigned char w, h, on_enter, n_actors, n_warps, bank;
                 const unsigned char *tiles; const unsigned char *coll;
                 const PjActor *actors; const PjWarp *warps; } PjMapInfo;
typedef struct { unsigned int tile_base; unsigned char frames; } PjSprite;

#define PJ_MAP_COUNT 2
#define PJ_SPRITE_COUNT 1
#define PJ_TEXT_COUNT 13
#define PJ_SCRIPT_COUNT 4
#define PJ_START_MAP 0
#define PJ_START_X 9
#define PJ_START_Y 14
#define PJ_START_DIR 1
#define PJ_BG_TILE_COUNT 13
#define PJ_OBJ_TILE_COUNT 32
#define PJ_BOX_TILE 12
#define PJ_SLOT_BASE 13
#define PJ_FULL_GLYPH_COUNT 0
#define PJ_SCRIPT_BUF 2048

extern const PjMapInfo pj_maps[];
extern const PjSprite pj_sprites[];
extern const unsigned char pj_map0_tiles[]; BANKREF_EXTERN(pj_map0_tiles)
extern const unsigned char pj_map0_coll[];
extern const unsigned char pj_map0_actors[];
extern const unsigned char pj_map0_warps[];
extern const unsigned char pj_map1_tiles[]; BANKREF_EXTERN(pj_map1_tiles)
extern const unsigned char pj_map1_coll[];
extern const unsigned char pj_map1_actors[];
extern const unsigned char pj_map1_warps[];
extern const unsigned char pj_bg_tiles[]; BANKREF_EXTERN(pj_bg_tiles)
extern const unsigned char pj_obj_tiles[]; BANKREF_EXTERN(pj_obj_tiles)
extern const unsigned char pj_glyphs_half[]; BANKREF_EXTERN(pj_glyphs_half)
extern const unsigned char pj_glyphs_full[]; BANKREF_EXTERN(pj_glyphs_full)
extern const unsigned int pj_text_offs[]; BANKREF_EXTERN(pj_text_offs)
extern const unsigned char pj_texts[]; BANKREF_EXTERN(pj_texts)
extern const unsigned int pj_script_offs[]; BANKREF_EXTERN(pj_script_offs)
extern const unsigned char pj_scripts[]; BANKREF_EXTERN(pj_scripts)

#endif
