// edge/compiler/emit.ts — residualize the CompiledFilm into runtime/gen_data.c.
// Everything is plain C arrays in ROM; no container parsing at runtime.

import type { CompiledFilm, CompiledScene } from "./index.ts";

/** gen_music.s — PCM tracks land in ROM via .incbin (a 1 MB C literal is silly). */
export function emitGenMusic(film: CompiledFilm): string {
  const lines: string[] = [
    "/* gen_music.s — GENERATED by edge/compiler. Do not edit. */",
    ".section .rodata",
  ];
  film.tracks.forEach((t, i) => {
    lines.push(`.balign 4`, `.global mus_${i}`, `mus_${i}:`, `.incbin "${t.path}"`);
  });
  lines.push(".balign 4", "");
  return lines.join("\n");
}

function u8arr(name: string, data: Uint8Array): string {
  const lines: string[] = [`static const u8 ${name}[] = {`];
  for (let i = 0; i < data.length; i += 24) {
    lines.push("  " + Array.from(data.subarray(i, i + 24)).join(",") + ",");
  }
  lines.push("};");
  return lines.join("\n");
}

function u16arr(name: string, data: Uint16Array | number[]): string {
  const arr = Array.from(data);
  const lines: string[] = [`static const u16 ${name}[] = {`];
  for (let i = 0; i < arr.length; i += 16) {
    lines.push("  " + arr.slice(i, i + 16).map((v) => "0x" + v.toString(16)).join(",") + ",");
  }
  lines.push("};");
  return lines.join("\n");
}

function u32arr(name: string, data: number[]): string {
  const lines: string[] = [`static const u32 ${name}[] = {`];
  for (let i = 0; i < data.length; i += 12) {
    lines.push("  " + data.slice(i, i + 12).map((v) => String(v >>> 0)).join(",") + ",");
  }
  lines.push("};");
  return lines.join("\n");
}

export function emitGenData(film: CompiledFilm): string {
  const parts: string[] = [
    "/* gen_data.c — GENERATED by edge/compiler. Do not edit. */",
    '#include "edge.h"',
    "",
  ];

  film.scenes.forEach((s: CompiledScene, i: number) => {
    parts.push(u16arr(`s${i}_pal_bg`, s.palBg));
    parts.push(u16arr(`s${i}_pal_obj`, s.palObj));
    parts.push(u8arr(`s${i}_tiles_main`, s.tilesMain));
    if (s.nShared) parts.push(u8arr(`s${i}_tiles_shared`, s.tilesShared));
    parts.push(u16arr(`s${i}_map_main`, s.mapMain));
    if (s.mapFar) parts.push(u16arr(`s${i}_map_far`, s.mapFar));
    if (s.mapSky) parts.push(u16arr(`s${i}_map_sky`, s.mapSky));
    if (s.gradient) parts.push(u16arr(`s${i}_grad`, s.gradient));
    if (s.objTiles.length) parts.push(u8arr(`s${i}_obj`, s.objTiles));
    if (s.protos.length) {
      const rows = s.protos
        .map((p) => `  {${p.tileBase},${p.w},${p.h},${p.frames},${p.palbank},${p.fps},${p.walkFpd}},`)
        .join("\n");
      parts.push(`static const EdgeProto s${i}_protos[] = {\n${rows}\n};`);
    }
    parts.push(u8arr(`s${i}_cue`, s.cue));
    parts.push(u16arr(`s${i}_cue_offs`, s.cueOffs));
    if (s.stage) {
      const st = s.stage;
      parts.push(u16arr(`s${i}_pal_sande`, st.palSande));
      if (st.spawns.length) {
        const rows = st.spawns
          .map((sp) => `  {${sp.x},${sp.proto},${sp.behavior},${sp.hp},${sp.wave}},`)
          .join("\n");
        parts.push(`static const EdgeSpawn s${i}_spawns[] = {\n${rows}\n};`);
      }
      if (st.plats.length) {
        const rows = st.plats.map((p) => `  {${p[0]},${p[1]},${p[2]}},`).join("\n");
        parts.push(`static const EdgePlat s${i}_plats[] = {\n${rows}\n};`);
      }
      if (st.gates.length) {
        const rows = st.gates.map((gt) => `  {${gt[0]},${gt[1]}},`).join("\n");
        parts.push(`static const EdgeGate s${i}_gates[] = {\n${rows}\n};`);
      }
      parts.push(
        `static const EdgeStage s${i}_stage = { ${st.playerProto}, ${st.hpMax}, ${st.sandeMax}, ` +
          `${st.exitKind}, ${st.groundY}, ${st.length}, ` +
          `${st.hpVar}, ${st.sandeVar}, ${st.killsVar}, ${st.deathsVar}, ` +
          `${st.spawns.length ? `s${i}_spawns` : "0"}, ${st.spawns.length}, ` +
          `${st.plats.length ? `s${i}_plats` : "0"}, ${st.plats.length}, ` +
          `${st.gates.length ? `s${i}_gates` : "0"}, ${st.gates.length}, ` +
          `${st.boss}, ${st.bossPhaseHp}, s${i}_pal_sande };`,
      );
    }
    if (s.world) {
      const w = s.world;
      parts.push(u8arr(`s${i}_solid`, w.solid));
      if (w.npcs.length) {
        const rows = w.npcs
          .map((n) => `  {${n.cx},${n.cy},${n.dir},${n.slot},${n.proto},${n.cue},${n.solid}},`)
          .join("\n");
        parts.push(`static const EdgeNpc s${i}_npcs[] = {\n${rows}\n};`);
      }
      if (w.trigs.length) {
        const rows = w.trigs
          .map((t) => `  {${t.cx},${t.cy},${t.w},${t.h},${t.kind},${t.value},${t.cue}},`)
          .join("\n");
        parts.push(`static const EdgeTrig s${i}_trigs[] = {\n${rows}\n};`);
      }
      parts.push(
        `static const EdgeWorld s${i}_world = { ${w.cols}, ${w.rows}, s${i}_solid, ` +
          `${w.startCx}, ${w.startCy}, ${w.startDir}, ${w.playerSlot}, ${w.playerProto}, ` +
          `${w.npcs.length ? `s${i}_npcs` : "0"}, ${w.npcs.length}, ` +
          `${w.trigs.length ? `s${i}_trigs` : "0"}, ${w.trigs.length} };`,
      );
    }
    parts.push("");
  });

  parts.push(u32arr("film_text_offs", film.textOffs));
  parts.push(u8arr("film_text_blob", film.textBlob));
  parts.push(u8arr("film_glyphs", film.glyphs));
  parts.push(u8arr("film_ui_bg", film.uiBg));
  parts.push(u8arr("film_ui_obj", film.uiObj));
  if (film.tracks.length) {
    film.tracks.forEach((_, i) => parts.push(`extern const s8 mus_${i}[]; /* gen_music.s */`));
    const rows = film.tracks.map((t, i) => `  {mus_${i}, ${t.samples}u, ${t.loop}},`).join("\n");
    parts.push(`static const EdgeTrack film_tracks[] = {\n${rows}\n};`);
  }
  parts.push("");

  const rows = film.scenes.map((s, i) => {
    const f = (b: boolean, t: string) => (b ? t : "0");
    return [
      "  {",
      `s${i}_pal_bg, s${i}_pal_obj,`,
      `s${i}_tiles_main, ${s.nMain},`,
      `${s.nShared ? `s${i}_tiles_shared` : "0"}, ${s.nShared},`,
      `s${i}_map_main,`,
      `${f(!!s.mapFar, `s${i}_map_far`)}, ${f(!!s.mapSky, `s${i}_map_sky`)},`,
      `${s.mapSz},`,
      `${s.farFacQ8}, ${s.skyFacQ8}, ${s.farVxQ8}, ${s.skyVxQ8},`,
      `${f(!!s.gradient, `s${i}_grad`)},`,
      `${s.objTiles.length ? `s${i}_obj` : "0"}, ${s.objTiles.length},`,
      `${s.protos.length ? `s${i}_protos` : "0"}, ${s.protos.length},`,
      `s${i}_cue, ${s.cue.length},`,
      `s${i}_cue_offs, ${s.cueOffs.length},`,
      `${s.kind}, ${f(!!s.world, `&s${i}_world`)}, ${f(!!s.stage, `&s${i}_stage`)},`,
      `${s.cam0}, ${s.camMin}, ${s.camMax},`,
      `${s.rasterMode}, ${s.rasterAmp}, ${s.letterbox0}, 0x${s.backdrop.toString(16)}`,
      "},",
    ].join(" ");
  });
  parts.push(`static const EdgeScene film_scenes[] = {\n${rows.join("\n")}\n};`);
  parts.push("");
  parts.push(
    `const EdgeFilm film = { film_scenes, ${film.scenes.length}, film_text_offs, film_text_blob, ` +
      `${film.textOffs.length}, film_glyphs, ${film.nHalfcells}, film_ui_bg, film_ui_obj, ${film.uiObj.length}, ` +
      `${film.tracks.length ? "film_tracks" : "0"}, ${film.tracks.length} };`,
  );
  parts.push("");
  return parts.join("\n");
}
